language: node_js
script:
  - npm run precommit
deploy:
  provider: heroku
  api_key:
    secure: Ne6Yw+bHSAPDEZyfZK4ag6nrEsXj/SBX1q6MGus6rd0p6bpIB6NSjKbeuiGITUifdDnmexhMQgcyisVldKKLE+z9wObyNDOgm1BqGYd+OV/Q8KRlTQsfRMLmbeEJkDyp1ADaEoya1/WGVC/YKZ15XCPtRzl/O1H1lyLh8pZMldk3lKUET7ljLgJNDW6YbTh4cdQRtKx7DkzExf6xoN1kpkPOT6WYP6Q2yC78vqP1ZEF8x3A6GYVjsii43f7roX2NTe6MqBAp23SJddTsgqO/i1QUm981zSf480AX27z5W/oIQV8kkLnVmfXbL6N7ZQ6aXgLJSJGg0lMfS4uZghvgKfj8aju0RVKREBBIjmA/XN4+v9URXEuyH8nsWL6XWIxjmERtgbkADc12FhjffGtSi6FkEO6bM8YsK7raLV1e25MDgYIOFgSCaWqL8R5PIiMqMEOy8O0axGzYtBMUWPvYoIREThQ72pYopIPxfHLYTLCmaD8UPuuSFujaHKoiIFQoNyp3FF1faX+DYiSr9zisCorlNizT84Wl4nZRuWblpOZ/XYcWGYU5k8/1viA+X+AubG7RksDfOB0WiIzDq6Sgt1goXClIZdTnie73sKeh00MehbZYQfkjB02aw4k9qBj2QYHBQvDksXfoC/xiGXcXeTv0pxXhnofq6yqFsx4Gpz8=
  app: watch_edition_react
  on:
    repo: twlevelup/watch_edition_react
