language: node_js
deploy:
  provider: heroku
  api_key:
    secure: c5QDLnH1enaSg01VR9wl7tX7tYJOJ/afGEDPh2+QKzxHFIoJAIku9c0WCVkkeI8we2B5d0o5wu5+HXCFgDEsL50a3E5I2/CXCU2tkATHnvZZcjMvKyuOhwlrtcb216uKcCIrX4jTcZFXzmI7kwUBE9LcN8f2nKARqg1RN1WqvzySQyOUx5O1K+K6Q+VSKDAg6bszsRglCUjPV8zJ2yZv6k0fJFsAtmqzBgE/GahfN1jwmgMSpWMmwmyzYCadmX31NDHVIIL3FKBAOXsCQbfym5TjXoC84O7/QXRzxU5b4yU8P2Vaf0apHIGc7z1g7whLCO9B/MtlBQXGCcwnxoZDbK7nSwsgFmfhplKav4RjWeUejaiBzSOX/1aeufF49NezVRG8GhohKtH7C3B1/EIABR0pJJlm5rKs8ofwyU4XRTJO9AU7UejOolHfEQNoK39bk+CDSPajIV+gCe95B9m4JNNrI3Fm9tNxoAkT0RU8iDpbtOq391PMcQglz6l5Znxp/F6fKtbo+W1JvwODn5qI+enw+/wi2IoOXpOJKxRpNraJVEJ53qjGD7fwfDTxiW2J6NewKqTJaRTzhyq8PLtSHf2PyV3q0t/XBNWxPL722h4SBk9y98tpbhituMOmDk3Rx9jCb3BbhswKmwLBwnTZGfNhnbih4aOevErxtwBw1aE=
  app: twlevelup-watch-edition
  on:
    repo: twlevelup/watch_edition_react
